export const defaultTemplateFormValues = {
  name: '',
  firstName: '',
  familyName: '',
  gender: '',
  dateofBirth: '',
  hhid: '',
  mobilePhoneID: '',
  govIDType: '',
  govIDNumber: '',
  otherIDType: '',
  otherIDNumber: '',
  assistanceDetails: '',
  activity: '',
  currency: '',
  currencyAmount: '',
  startDate: '',
  endDate: '',
  frequency: '',
  adminLevel1: '',
  adminLevel2: '',
  adminLevel3: '',
  adminLevel4: '',
};

export const STANDARDIZED_TEMPLATE_FIELDS: { [key: string]: string } = {
  firstName: 'string',
  familyName: 'string',
  gender: 'string',
  dateofBirth: 'DateTime',
  hhid: 'string',
  mobilePhoneID: 'integer',
  govIDType: 'string',
  govIDNumber: 'string',
  otherIDType: 'string',
  otherIDNumber: 'string',
  assistanceDetails: 'string',
  activity: 'string',
  currency: 'string',
  currencyAmount: 'integer',
  startDate: 'DateTime',
  endDate: 'DateTime',
  frequency: 'string',
  adminLevel1: 'string',
  adminLevel2: 'string',
  adminLevel3: 'string',
  adminLevel4: 'string',
};
