export const defaultSentReferralFormFormValues = {
  isUrgent: false,
  serviceCategory: '',
  subactivities: [],
  subactivitiesIds: [],
  organizationReferredTo: undefined,
  displacementStatus: '',
  householdSize: '',
  householdMonthlyIncome: '',
  householdsVulnerabilityCriteria: [],
  firstName: '',
  patronymicName: '',
  surname: '',
  dateOfBirth: undefined,
  gender: '',
  taxId: '',
  address: '',

  oblast: '',
  ryon: '',
  hromada: '',
  settlement: '',

  administrativeRegion1: null,
  administrativeRegion2: null,
  administrativeRegion3: null,
  administrativeRegion4: null,

  email: '',
  phone: '',
  contactPreference: 'email',
  restrictions: '',
  consent: false,
  required: '',
  needForService: '',
  isSeparated: false,
  caregiver: '',
  relationshipToChild: '',
  caregiverEmail: '',
  caregiverPhone: '',
  isCaregiverInformed: 'false',
  caregiverExplanation: '',
  caregiverNote: '',
  focalPoint: undefined,
  status: '',
  isDraft: false,
  userCreated: undefined,
  files: [],
  focalPointId: '',
  noTaxId: false,
  isMinor: false,
  caregiverContactPreference: 'email',
};
