export const defaultTemplateFormValues = {
  name: '',
  firstName: '',
  familyName: '',
  gender: '',
  dateofBirth: '',
  communityID: '',
  hhid: '',
  mobilePhoneID: '',
  govIDType: '',
  govIDNumber: '',
  otherIDType: '',
  otherIDNumber: '',
  assistanceDetails: '',
  activity: '',
  currency: '',
  currencyAmount: '',
  startDate: '',
  endDate: '',
  frequency: '',
};
