export const defaultTemplateFormValues = {
  name: '',
  firstName: '',
  familyName: '',
  gender: '',
  dateofBirth: '',
  hhid: '',
  mobilePhoneID: '',
  govIDType: '',
  govIDNumber: '',
  otherIDType: '',
  otherIDNumber: '',
  assistanceDetails: '',
  activity: '',
  currency: '',
  currencyAmount: '',
  startDate: '',
  endDate: '',
  frequency: '',
  adminLevel1: '',
  adminLevel2: '',
  adminLevel3: '',
  adminLevel4: '',
};
