import { resToOrganization } from '@/services/organizations';

import { Referral } from './types';
import { resToUser } from '../users';
import { resToStorageFile } from '../storage';

export const resToReferral = (res: any): Referral => {
  return {
    id: res.id,
    isUrgent: res.isUrgent ?? false,
    serviceCategory: res.serviceCategory ?? '',
    subactivities: res.subactivities ?? [],
    organizationReferredToId: res.organizationReferredToId ?? '',
    organizationReferredTo: res.organizationReferredTo ? resToOrganization(res.organizationReferredTo) : null,
    displacementStatus: res.displacementStatus ?? '',
    householdSize: res.householdSize ?? '',
    householdMonthlyIncome: res.householdMonthlyIncome ?? '',
    householdsVulnerabilityCriteria: res.householdsVulnerabilityCriteria ?? [],
    firstName: res.firstName ?? '',
    patronymicName: res.patronymicName ?? '',
    surname: res.surname ?? '',
    dateOfBirth: new Date(res.dateOfBirth),
    gender: res.gender ?? '',
    taxId: res.taxId ?? '',
    address: res.address ?? '',
    oblast: res.oblast ?? '',
    ryon: res.ryon ?? '',
    hromada: res.hromada ?? '',
    settlement: res.settlement ?? '',
    email: res.email ?? '',
    phone: res.phone ?? '',
    contactPreference: res.contactPreference ?? '',
    restrictions: res.restrictions ?? '',
    consent: res.consent ?? false,
    required: res.required ?? '',
    needForService: res.needForService ?? '',
    isSeparated: res.isSeparated ?? false,
    caregiver: res.caregiver ?? '',
    relationshipToChild: res.relationshipToChild ?? '',
    caregiverEmail: res.caregiverEmail ?? '',
    caregiverPhone: res.caregiverPhone ?? '',
    caregiverContactPreference: res.caregiverContactPreference ?? '',
    isCaregiverInformed: res.isCaregiverInformed.toString() ?? 'false',
    caregiverExplanation: res.caregiverExplanation ?? '',
    caregiverNote: res.caregiverPhone ?? '',
    focalPointId: res.focalPointId ?? '',
    focalPoint: res.focalPoint ? resToUser(res.focalPoint) : null,
    status: res.status ?? '',
    isDraft: res.isDraft ?? false,
    fileIds: res.fileIds ? res.fileIds.map(String) : [],
    organizationCreated: res.organizationCreated ? resToOrganization(res.organizationCreated) : null,
    userCreated: res.userCreated ? resToUser(res.userCreated) : null,
    files: res.files ? res.files.map(resToStorageFile) : [],

    // familyName: string;
    // methodOfContact: res.methodOfContact ?? '',
    // contactDetails: res.contactDetails ?? '',
    // note: res.note ?? '',
    // createdAt: res.createdAt ? new Date(res.createdAt) : null,
    // updatedAt: res.updatedAt ? new Date(res.updatedAt) : null,
  };
};

export const referralPostToReq = (data: any): Omit<Referral, 'id'> => {
  const req: any = {
    isUrgent: data.isUrgent,
    organizationReferredToId: data.organizationReferredTo?.id,
    serviceCategory: data.serviceCategory,
    subactivities: data.subactivities,
    displacementStatus: data.displacementStatus,
    householdSize: data.householdSize,
    householdMonthlyIncome: data.householdMonthlyIncome,
    householdsVulnerabilityCriteria: data.householdsVulnerabilityCriteria,
    firstName: data.firstName,
    patronymicName: data.patronymicName,
    surname: data.surname,
    dateOfBirth: data.dateOfBirth ? data.dateOfBirth.toISOString() : null,
    gender: data.gender,
    taxId: data.taxId,
    address: data.address,
    oblast: data.oblast,
    ryon: data.ryon,
    hromada: data.hromada,
    settlement: data.settlement,
    email: data.email,
    phone: data.phone,
    contactPreference: data.contactPreference,
    restrictions: data.restrictions,
    consent: data.consent,
    required: data.required,
    needForService: data.needForService,
    fileIds: data.files?.map((i: any) => i.id) || [],
    isSeparated: data.isSeparated,
    caregiver: data.caregiver,
    relationshipToChild: data.relationshipToChild,
    caregiverEmail: data.caregiverEmail,
    caregiverPhone: data.caregiverPhone,
    caregiverContactPreference: data.caregiverContactPreference,
    isCaregiverInformed: data.isCaregiverInformed === 'true',
    caregiverExplanation: data.caregiverExplanation,
    caregiverNote: data.caregiverNote,
    isDraft: data.isDraft,
    focalPointId: data.focalPoint?.id ?? undefined,
    methodOfContact: data.methodOfContact,
    note: data.note,
    organizationId: data.organizationReferredTo?.id,
    status: data.status,
  };

  // contactDetails: data.contactDetails,
  // familyName: data.familyName,

  return req;
};

export const referralPatchToReq = (data: any): Omit<Referral, 'id'> => {
  const req: any = {
    isUrgent: data.isUrgent,
    organizationReferredToId: data.organizationReferredTo?.id,
    serviceCategory: data.serviceCategory,
    subactivities: data.subactivities,
    displacementStatus: data.displacementStatus,
    householdSize: data.householdSize,
    householdMonthlyIncome: data.householdMonthlyIncome,
    householdsVulnerabilityCriteria: data.householdsVulnerabilityCriteria,
    firstName: data.firstName,
    patronymicName: data.patronymicName,
    surname: data.surname,
    dateOfBirth: data.dateOfBirth ? data.dateOfBirth.toISOString() : null,
    gender: data.gender,
    taxId: data.taxId,
    address: data.address,
    oblast: data.oblast,
    ryon: data.ryon,
    hromada: data.hromada,
    settlement: data.settlement,
    email: data.email,
    phone: data.phone,
    contactPreference: data.contactPreference,
    restrictions: data.restrictions,
    consent: data.consent,
    required: data.required,
    needForService: data.needForService,
    fileIds: data.files?.map((i: any) => i.id) || [],
    isSeparated: data.isSeparated,
    caregiver: data.caregiver,
    relationshipToChild: data.relationshipToChild,
    caregiverEmail: data.caregiverEmail,
    caregiverPhone: data.caregiverPhone,
    caregiverContactPreference: data.caregiverContactPreference,
    isCaregiverInformed: data.isCaregiverInformed === 'true',
    caregiverExplanation: data.caregiverExplanation,
    caregiverNote: data.caregiverNote,
    focalPointId: data.focalPoint?.id ?? undefined,
    status: data.status,
    isDraft: data.isDraft,

    // familyName: data.familyName,
    // methodOfContact: data.methodOfContact,
    // contactDetails: data.contactDetails,
    // note: data.note,
    // organizationId: data.organizationReferredTo?.id,
  };

  return req;
};
